// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_WINDOWS_API_KEY']!,
    appId: '1:124211341742:web:911aaaf0b15aafc0d3c03f',
    messagingSenderId: '124211341742',
    projectId: 'fruitify-c3b7c',
    authDomain: 'fruitify-c3b7c.firebaseapp.com',
    storageBucket: 'fruitify-c3b7c.firebasestorage.app',
    measurementId: 'G-51ZJJVXWBD',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!,
    appId: '1:124211341742:android:bccbb0e5f16acd26d3c03f',
    messagingSenderId: '124211341742',
    projectId: 'fruitify-c3b7c',
    storageBucket: 'fruitify-c3b7c.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:124211341742:ios:5bf376a44c0d4b8bd3c03f',
    messagingSenderId: '124211341742',
    projectId: 'fruitify-c3b7c',
    storageBucket: 'fruitify-c3b7c.firebasestorage.app',
    iosBundleId: 'com.example.fruitify',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:124211341742:ios:5bf376a44c0d4b8bd3c03f',
    messagingSenderId: '124211341742',
    projectId: 'fruitify-c3b7c',
    storageBucket: 'fruitify-c3b7c.firebasestorage.app',
    iosBundleId: 'com.example.fruitify',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_WINDOWS_API_KEY']!,
    appId: '1:124211341742:web:65eada00780d6671d3c03f',
    messagingSenderId: '124211341742',
    projectId: 'fruitify-c3b7c',
    authDomain: 'fruitify-c3b7c.firebaseapp.com',
    storageBucket: 'fruitify-c3b7c.firebasestorage.app',
    measurementId: 'G-6CWMK6LSTP',
  );
}
